name: docs

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up JDK11
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.9'
        java-package: jdk
        architecture: x64
    - name: Generate docs
      run: make docs
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: docs
        folder: docs
        target-folder: docs
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: lihram/tectonic-nix@v1.0
        with:
          file: "-o . report/report.tex"
      - name: Remove report sources
        run: "rm -rf report/"
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: docs
          clean: off
          folder: report
