name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
    - uses: actions/checkout@v2
    - name: Set up JDK11
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.9'
        java-package: jdk
        architecture: x64
    - run: make clean
    - run: make build
    - run: make test
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install Symbola
        run: sudo apt-get install fonts-symbola -y 
      - name: Compile LaTeX document
        uses: lihram/tectonic-nix
        with:
          file: "report/report.tex"
